services:
  coin-payment:
    build: .
    container_name: nodejs-coin-payment
    restart: unless-stopped
    ports:
      - '8039:8039'
    environment:
      - NODE_ENV=production
      - PORT=8039
      - DOMAIN_URL=https://coin-payment.m-gh.com
      - CALLBACK_URL=/api/webhook/callback
      - SUCCESS_URL=/payment/success
      - CANCEL_URL=/payment/cancel
    env_file:
      - .env
    volumes:
      # Mount logs directory for persistence (optional)
      - ./logs:/app/logs
    healthcheck:
      test: ['CMD', 'node', '-e', "require('http').get('http://localhost:8039/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


  # Optional: Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: coin-payment-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    profiles:
      - with-redis
