const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const bodyParser = require('body-parser');
const path = require('path');
const config = require('./config');

// Import routes
const paymentRoutes = require('./routes/payment');
const webhookRoutes = require('./routes/webhook');

const app = express();
const PORT = config.server.port;

// Generate nonce for CSP first
app.use((req, res, next) => {
  res.locals.nonce = require('crypto').randomBytes(16).toString('base64');
  next();
});

// Security middleware with dynamic CSP
app.use((req, res, next) => {
  helmet({
    contentSecurityPolicy: {
      directives: {
        ...helmet.contentSecurityPolicy.getDefaultDirectives(),
        "script-src": ["'self'", `'nonce-${res.locals.nonce}'`],
        "script-src-attr": [`'nonce-${res.locals.nonce}'`],
      },
    },
  })(req, res, next);
});

// CORS configuration
app.use(cors({
  origin: process.env.NODE_ENV === 'production' 
    ? [config.domain.url] 
    : ['http://localhost:3000', 'http://127.0.0.1:3000'],
  credentials: true
}));

// Body parsing middleware
app.use(bodyParser.json({ limit: '10mb' }));
app.use(bodyParser.urlencoded({ extended: true, limit: '10mb' }));

// Serve static files
app.use(express.static(path.join(__dirname, 'public')));

// API Routes
app.use('/api/payment', paymentRoutes);
app.use('/api/webhook', webhookRoutes);

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({
    status: 'OK',
    timestamp: new Date().toISOString(),
    environment: config.server.nodeEnv,
    domain: config.domain.url
  });
});

// Root endpoint
app.get('/', (req, res) => {
  res.json({
    message: 'NodeJS Coin Payment Service',
    description: 'PayID19.com integration for cryptocurrency payments',
    domain: config.domain.url,
    endpoints: {
      health: '/health',
      createInvoice: '/api/payment/create-invoice',
      getInvoices: '/api/payment/invoices',
      getBalance: '/api/payment/balance',
      getCurrencies: '/api/payment/currencies',
      webhook: '/api/webhook/callback'
    }
  });
});

// Payment success page
app.get('/payment/success', (req, res) => {
  const { order_id, invoice_id, status, return_url } = req.query;
  
  // Determine the return URL - prioritize return_url parameter, fallback to root
  const returnUrl = return_url || '/';
  
  // Use the nonce generated by middleware
  const nonce = res.locals.nonce;
  
  res.send(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Payment Successful</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style>
        body { font-family: Arial, sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; text-align: center; }
        .success { color: #28a745; }
        .container { background: #f8f9fa; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .details { background: white; padding: 20px; margin: 20px 0; border-radius: 5px; }
        .btn { display: inline-block; padding: 10px 20px; background: #28a745; color: white; text-decoration: none; border-radius: 5px; margin-top: 20px; cursor: pointer; border: none; }
        .btn:hover { background: #1e7e34; }
        .redirect-info { background: #d4edda; padding: 15px; margin: 20px 0; border-radius: 5px; border-left: 4px solid #28a745; }
        .countdown { font-weight: bold; color: #28a745; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1 class="success">✅ Payment Successful!</h1>
        <p>Your cryptocurrency payment has been processed successfully.</p>
        <div class="details">
          <p><strong>Order ID:</strong> ${order_id || 'N/A'}</p>
          <p><strong>Invoice ID:</strong> ${invoice_id || 'N/A'}</p>
          <p><strong>Status:</strong> ${status || 'Completed'}</p>
        </div>
        <p>Thank you for your payment!</p>
        ${return_url ? `
          <div class="redirect-info">
            <p>🔄 Automatically redirecting you back to the application in <span id="countdown" class="countdown">5</span> seconds...</p>
          </div>
          <button id="redirectBtn" class="btn" nonce="${nonce}">Return to Application Now</button>
        ` : `
          <a href="${returnUrl}" class="btn">Continue</a>
        `}
      </div>
      ${return_url ? `
        <script nonce="${nonce}">
          let countdown = 5;
          const countdownElement = document.getElementById('countdown');
          const redirectBtn = document.getElementById('redirectBtn');
          const returnUrl = '${returnUrl}';
          
          const redirectTimer = setInterval(() => {
            countdownElement.textContent = countdown;
            countdown--;
            if (countdown < 0) {
              clearInterval(redirectTimer);
              window.location.href = returnUrl;
            }
          }, 1000);
          
          redirectBtn.addEventListener('click', function() {
            clearInterval(redirectTimer);
            window.location.href = returnUrl;
          });
        </script>
      ` : ''}
    </body>
    </html>
  `);
});

// Payment cancel page
app.get('/payment/cancel', (req, res) => {
  const { order_id, invoice_id, return_url } = req.query;
  
  // Determine the return URL - prioritize return_url parameter, fallback to root
  const returnUrl = return_url || '/';
  
  // Use the nonce generated by middleware
  const nonce = res.locals.nonce;
  
  res.send(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Payment Cancelled</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style>
        body { font-family: Arial, sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; text-align: center; }
        .cancel { color: #dc3545; }
        .container { background: #f8f9fa; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        .details { background: white; padding: 20px; margin: 20px 0; border-radius: 5px; }
        .btn { display: inline-block; padding: 10px 20px; background: #007bff; color: white; text-decoration: none; border-radius: 5px; margin-top: 20px; cursor: pointer; border: none; }
        .btn:hover { background: #0056b3; }
        .redirect-info { background: #e7f3ff; padding: 15px; margin: 20px 0; border-radius: 5px; border-left: 4px solid #007bff; }
        .countdown { font-weight: bold; color: #007bff; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1 class="cancel">❌ Payment Cancelled</h1>
        <p>Your payment has been cancelled.</p>
        <div class="details">
          <p><strong>Order ID:</strong> ${order_id || 'N/A'}</p>
          <p><strong>Invoice ID:</strong> ${invoice_id || 'N/A'}</p>
        </div>
        <p>You can try again or contact support if you need assistance.</p>
        ${return_url ? `
          <div class="redirect-info">
            <p>🔄 Automatically redirecting you back to the application in <span id="countdown" class="countdown">3</span> seconds...</p>
          </div>
          <button id="redirectBtn" class="btn" nonce="${nonce}">Return to Application Now</button>
        ` : `
          <a href="${returnUrl}" class="btn">Return to Home</a>
        `}
      </div>
      ${return_url ? `
        <script nonce="${nonce}">
          let countdown = 3;
          const countdownElement = document.getElementById('countdown');
          const redirectBtn = document.getElementById('redirectBtn');
          const returnUrl = '${returnUrl}';
          
          const redirectTimer = setInterval(() => {
            countdownElement.textContent = countdown;
            countdown--;
            if (countdown < 0) {
              clearInterval(redirectTimer);
              window.location.href = returnUrl;
            }
          }, 1000);
          
          redirectBtn.addEventListener('click', function() {
            clearInterval(redirectTimer);
            window.location.href = returnUrl;
          });
        </script>
      ` : ''}
    </body>
    </html>
  `);
});

// Error handling middleware
app.use((err, req, res, next) => {
  console.error('Error:', err.stack);
  res.status(500).json({
    error: 'Internal Server Error',
    message: process.env.NODE_ENV === 'development' ? err.message : 'Something went wrong!'
  });
});

// 404 handler
app.use((req, res) => {
  res.status(404).json({
    error: 'Not Found',
    message: `Route ${req.method} ${req.path} not found`
  });
});

// Start server
app.listen(PORT, () => {
  console.log(`🚀 NodeJS Coin Payment Service running on port ${PORT}`);
  console.log(`🌐 Domain: ${config.domain.url}`);
  console.log(`📊 Environment: ${config.server.nodeEnv}`);
  console.log(`💰 PayID19 API: ${config.payid19.apiUrl}`);
  
  if (config.server.nodeEnv === 'development') {
    console.log(`\n📋 Available endpoints:`);
    console.log(`   Health Check: http://localhost:${PORT}/health`);
    console.log(`   API Docs: http://localhost:${PORT}/`);
    console.log(`   Create Invoice: POST http://localhost:${PORT}/api/payment/create-invoice`);
    console.log(`   Webhook: POST http://localhost:${PORT}/api/webhook/callback`);
  }
});

module.exports = app;
